# Generated by Django 4.1.7 on 2023-02-21 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirunpackage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chirunpackage',
            name='slug',
        ),
        migrations.AddField(
            model_name='chirunpackage',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
