# Generated by Django 4.1.7 on 2023-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_chirunpackage_id_remove_chirunpackage_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirunpackage',
            name='build_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chirunpackage',
            name='build_status',
            field=models.CharField(choices=[('building', 'Building'), ('built', 'Built'), ('error', 'Error during building')], default='error', max_length=10),
            preserve_default=False,
        ),
    ]
