# Generated by Django 4.1.7 on 2023-02-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_resourcelink'),
        ('lti1p3_tool_config', '0002_alter_ltitool_id_alter_ltitoolkey_id'),
        ('material', '0003_chirunpackage_build_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirunpackage',
            name='lti_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chirun_packages', to='lti.context'),
        ),
        migrations.AddField(
            model_name='chirunpackage',
            name='lti_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chirun_packages', to='lti1p3_tool_config.ltitool'),
        ),
    ]
