# Generated by Django 4.1.7 on 2023-02-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_chirunpackage_lti_context_chirunpackage_lti_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirunpackage',
            name='build_output',
        ),
        migrations.RemoveField(
            model_name='chirunpackage',
            name='build_status',
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('building', 'Building'), ('built', 'Built'), ('error', 'Error during building')], default='building', max_length=10)),
                ('output', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='material.chirunpackage')),
            ],
        ),
    ]
