# Generated by Django 4.1.7 on 2023-03-01 13:22

from django.db import migrations, models
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_chirunpackage_build_output_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirunpackage',
            options={'ordering': (django.db.models.functions.text.Lower('name'), 'uid')},
        ),
        migrations.AlterModelOptions(
            name='compilation',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AddField(
            model_name='chirunpackage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
