# Generated by Django 4.1.7 on 2023-03-06 15:13

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_chirunpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirunpackage',
            options={'ordering': (django.db.models.functions.text.Lower('name'), '-created', 'uid')},
        ),
    ]
