# Generated by Django 4.1.7 on 2023-05-11 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_chirunpackage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirunpackage',
            name='edit_uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
