# Generated by Django 4.1.7 on 2023-05-11 09:09

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    ChirunPackage = apps.get_model('material', 'ChirunPackage')
    for row in ChirunPackage.objects.all():
        row.edit_uid = uuid.uuid4()
        row.save(update_fields=['edit_uid'])

class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_chirunpackage_edit_uid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
