# Generated by Django 4.1.7 on 2023-05-11 09:09

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20230511_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirunpackage',
            name='edit_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
