# Generated by Django 4.2.4 on 2023-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_separate_package_lti_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='status',
            field=models.CharField(choices=[('building', 'Building'), ('built', 'Built'), ('error', 'Error during building'), ('not_built', 'Not built')], default='not_built', max_length=10),
        ),
    ]
