# Generated by Django 4.2.4 on 2023-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_alter_compilation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirunpackage',
            name='git_status',
            field=models.CharField(choices=[('cloning', 'Cloning from the source repository.'), ('updating', 'Updating from the source repository.'), ('ready', 'Ready to use')], default='cloning', max_length=10),
        ),
        migrations.AddField(
            model_name='chirunpackage',
            name='git_url',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Git URL'),
        ),
        migrations.AddField(
            model_name='chirunpackage',
            name='git_username',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Username'),
        ),
    ]
