# Generated by Django 4.2.4 on 2023-10-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_chirunpackage_git_status_chirunpackage_git_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Finished'), ('error', 'Ended with an error')], default='running', max_length=10)),
                ('output', models.TextField(blank=True, default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_interactions', to='material.chirunpackage')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
