# Generated by Django 4.2.4 on 2023-12-12 11:11

from django.conf import settings
from django.db import migrations, models
from pathlib import Path
import shutil

build_logs_path = Path() / settings.MEDIA_ROOT / 'chirun-packages' / 'build-logs'

def make_log_files(apps, schema_editor):
    Compilation = apps.get_model('material', 'Compilation')

    for c in Compilation.objects.all():
        d = build_logs_path / str(c.package.pk) / str(c.pk)
        d.mkdir(exist_ok=True, parents=True)
        with open(d / 'stdout.txt', 'w') as f:
            f.write(c.output)

def delete_log_files(apps, schema_editor):
    if build_logs_path.exists():
        shutil.rmtree(build_logs_path)

class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_gitinteraction'),
    ]

    operations = [
        migrations.RunPython(make_log_files, delete_log_files),

        migrations.RemoveField(
            model_name='compilation',
            name='output',
        ),

        migrations.AlterField(
            model_name='chirunpackage',
            name='git_status',
            field=models.CharField(choices=[('cloning', 'Cloning from the source repository.'), ('updating', 'Updating from the source repository.'), ('ready', 'Ready to use'), ('error', 'There was an error fetching from the source repository.')], default='cloning', max_length=10),
        ),
    ]
