# Generated by Django 4.2.6 on 2024-02-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_resourcelink'),
        ('material', '0017_packagelaunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelaunch',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='lti.resourcelink'),
        ),
        migrations.AlterField(
            model_name='packagelaunch',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='material.chirunpackage'),
        ),
    ]
