# Generated by Django 4.2.6 on 2024-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_alter_packagelaunch_link_alter_packagelaunch_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirunpackage',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
