# Generated by Django 4.2.4 on 2024-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_chirunpackage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirunpackage',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
