# Generated by Django 4.1.7 on 2023-02-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lti1p3_tool_config', '0002_alter_ltitool_id_alter_ltitoolkey_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.CharField(max_length=200)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='lti1p3_tool_config.ltitool')),
            ],
        ),
    ]
