# Generated by Django 4.1.7 on 2023-02-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0002_alter_ltitool_id_alter_ltitoolkey_id'),
        ('lti', '0002_context_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='lti.context')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='lti1p3_tool_config.ltitool')),
            ],
        ),
    ]
