base_dir: {BASE}
code: {GUID}
root_url: '{base}/{code}/{theme}/'
structure: 
  - type: document 
    sidebar: True 
    topbar: True
    footer: True
    source: {DOCUMENT}
themes: 
  - title: Default
    source: default
    path: default
build_pdf: True
