base_dir: {BASE}
code: {GUID}
year: {}
root_url: '{base}/{code}/{theme}/'
structure: 
  - type: standalone
    sidebar: False
    topbar: False
    footer: True
    source: {DOCUMENT}
    title: "Document: {DOCUMENT}"
    splitlevel: 0
themes: 
  - title: Standalone
    source: default
    path: default
build_pdf: True
