base_dir: {BASE}
code: {GUID}
root_url: '{base}/{code}/{theme}/'
structure: 
  - type: document 
    title: {DOCUMENT}
    sidebar: false
    topbar: false
    footer: true
    source: {DOCUMENT}
  - type: introduction
    topbar: false
    source: empty.md
themes: 
  - title: Standalone
    source: default
    path: default
build_pdf: True
