base_dir: {BASE}
code: {GUID}
root_url: '{base}/{code}/{theme}/'
structure: 
  - type: standalone
    source: {DOCUMENT}
themes: 
  - title: Standalone
    source: standalone
    path: default
build_pdf: True
