base_dir: {BASE}
code: {GUID}
year: {}
author: ""
title: ""
structure: 
  - type: {ITEMTYPE}
    sidebar: {SIDEBAR}
    topbar: False
    footer: True
    source: {DOCUMENT}
    title: "{TITLE}"
    splitlevel: {SPLITLEVEL}
themes: 
  - title: Standalone
    source: default
    path: default
build_pdf: {BUILDPDF}
